title: Reginald Sourn
description: Innovator Guys
author: Reginald Sourn
avatar: /profile.jpg
email: sourn.rithy@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:
  
# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ReginaldSourn
  card: summary
logo: profile.jpg
social:
  name: ReginaldSourn
  links:
    - https://twitter.com/ReginaldSourn
    - https://www.facebook.com/ngzhio
    - https://github.com/ReginaldSourn
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
